Update ocpp-server.js
Add try/catch to prevent 
SyntaxError: Unexpected token <various like \n or ]> in JSON at position ???
leading to restart of nodered every few hours.
Always expect faulty data